apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thumper.fullname" . }}
  labels:
    {{- include "thumper.labels" . | nindent 4 }}
data:
  THUMPER_BASE_URL: {{ .Values.config.baseUrl | quote }}
  THUMPER_DASHBOARD_REFRESH: {{ .Values.config.dashboardRefresh | quote }}
