{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thumper.fullname" . }}
  labels:
    {{- include "thumper.labels" . | nindent 4 }}
type: Opaque
stringData:
  THUMPER_ENROLL_TOKEN: {{ .Values.secrets.enrollToken | quote }}
  THUMPER_INSTALL_TOKEN: {{ .Values.secrets.installToken | quote }}
  THUMPER_DB: {{ include "thumper.databaseUrl" . | quote }}
{{- end }}
